### ISSUE TITLE
Key shouldn't be stored in NVM

### ISSUE THREAD

**Issue by btchip** [coranos/blue-app-neo#2]
https://github.com/coranos/blue-app-neo/blob/4787c9d97ce5d11b6255cc74fbfc9f9818eb9d0a/src/main.c#L313

it's a better practice to derive the key dynamically when the application is opened

**Comment by coranos** [comment]
Please reference an example where this is done.
I could not find an example in your example apps:
https://github.com/coranos/blue-sample-apps/

**Comment by btchip** [comment]
Just do the same thing in place and keep the key in RAM - for example with Ripple https://github.com/LedgerHQ/blue-app-xrp/blob/master/src/main.c#L1836

**Comment by coranos** [comment]
So, you want the client code to pass the key in as part of the transaction? I see it reads from G_io_apdu_buffer

**Comment by btchip** [comment]
No. Have your path in a static const and derive the key whenever you need it.

**Comment by coranos** [comment]
I'm not understanding.

I have the path in a static variable:
static unsigned int BIP44_PATH[BIP44_PATH_LEN];
Are you just asking me to make it "static const"?

I populate it when the app is opened, int main(void), directly before I use it in the call to
the call to os_perso_derive_node_bip32.
Are you asking me to move this initialization from main() to some other method?

that's a direct copy of your blue-app-samplesign app where you init N_privateKey in main():
https://github.com/coranos/blue-sample-apps/blob/master/blue-app-samplesign/src/main.c

So I'm not sure what you are asking me to do.

**Comment by btchip** [comment]
Just perform the derivation every time you need the key, and keep the key in RAM - there's no reason to write that key to flash (it was done in the sample to demonstrate how to write to flash, basically)

**Comment by coranos** [comment]
Ok, figured it out. The wallet will pass the path in along with the rest of the transaction.
