### ISSUE TITLE
Check for raw_tx overflow

### ISSUE THREAD

**Issue by btchip** [coranos/blue-app-neo#4]
https://github.com/coranos/blue-app-neo/blob/4787c9d97ce5d11b6255cc74fbfc9f9818eb9d0a/src/main.c#L133

Current transport code doesn't check bounds

**Comment by coranos** [comment]
issue is fixed, and a unit test added to demo.py.
https://github.com/coranos/blue-app-neo/commit/304e66ab18622a73b2769575eced2a22fadcd8a7
